### ISSUE TITLE
 Observing error message 500 with API: list-of-device-interfaces and list-of-actual-device-equipment

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MultiDomainInventoryProxy#23]
Observing error message 500  with API: /v1/provide-list-of-device-interfaces and /v1/provide-list-of-actual-device-equipment

Logs:
{
  "code": 500,
  "message": "Request failed with status code 400"
}

Note:  Response observed for both APIs  from MicrowaveDeviceInventory

**Comment by paulBMentopolis** [comment]
Resolved in tag v1.0.1_test

**Comment by paulBMentopolis** [comment]
Closed as discussed with Andreas Lattoch
