### ISSUE TITLE
Historical-performance - Specification of MDIP needs to be aligned with MWDI 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MultiDomainInventoryProxy#24]
Specification of MDIP needs to be aligned with MWDI .
ex: MAC-interface historical-performances is not supported in MWDI but still the API is available in MDIP.

VLAN -interface historical-performances is not supported in MWDI but still the API is available in MDIP.

``` 
API :http://xx.xxx/core-model-1-4:network-control-domain=cache/control-construct=xxx/logical-termination-point=xxx/layer-protocol=xxx/mac-interface-1-0:mac-interface-pac/mac-interface-historical-performances

```
/core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/vlan-interface-1-0:vlan-interface-pac/vlan-interface-historical-performances

```

**Comment by MFMentopolis** [comment]
I am assigning this issue to the application owner, since it is a specification issue.

**Comment by kmohr-soprasteria** [comment]
have already been removed
