### ISSUE TITLE
vlan-interface-historical-performances to be removed

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MultiDomainInventoryProxy#5]
The serviceList/oas/configFile contain entries for a vlan-interface-historical-performances service, but the [VLAN Interface UML diagram](https://github.com/openBackhaul/vlanInterface/blob/tsp/VlanInterface_1.0.0-tsp.220407.1810+overview.1.png) does not contain historical-performances. So this service might be obsolete and needs to be removed together with entries for the related MWDI operation client.

```
        - operation-name: /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/vlan-interface-1-0:vlan-interface-pac/vlan-interface-historical-performances
          uuid: mdip-1-0-0-op-s-is-264
```

(If the service is not needed, the related service would also need to be deleted from the MWDI specification.)

**Comment by openBackhaul** [comment]
Yes, correct vlan-interface-historical-performances does not exist in the ONF definition.
The corresponding cache path needs to be deleted from the MDIP specifications.
