### ISSUE TITLE
?fields filter is not effective (even if URL encoded)

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MultiDomainInventoryProxy#51]
GET http://10.118.125.211:3013/core-model-1-4:network-control-domain=cache/control-construct=513559991A
provides responseBody with 37947 lines.

GET http://10.118.125.211:3013/core-model-1-4:network-control-domain=cache/control-construct=513559991A%3Ffields%3Dlogical-termination-point%28ltp-augment-1-0%3Altp-augment-pac%3Blayer-protocol%28layer-protocol-name%29%29
provides responseBody with 37947 lines, too.

**Comment by paulBMentopolis** [comment]
Retested the service with the same mount on lab MDIP, fields filter is working and encoded correctly.

![Screenshot 2024-04-08 122517](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/148756388/1401febb-1135-46c6-8181-a8795f84164f)

![Screenshot 2024-04-08 122625](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/148756388/6df20e10-fa1f-4f02-9169-72cee6b9cc4b)

Not 100% sure if this is the issue, but in your request, it seems there is an encoding error in this part:
".../control-construct=513559991A**%3F**fields%3Dlogical-termination-point". The "?" after the mount should not be encoded.

**Comment by openBackhaul** [comment]
Yes, after changing from:
- ... network-control-domain=cache/control-construct=513559991A%3Ffields%3Dlogical-termination-point%28ltp- ...
to
- ... network-control-domain=cache/control-construct=513559991A?fields=logical-termination-point%28ltp- ...
MDIP fields filter was effective.

Issue to be closed without action.
