### ISSUE TITLE
Comparison ALAP & MDIP Parameters & Headers

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MultiDomainInventoryProxy#6]
Comparison between ALAP & MDIP headers + parameters shows that they are used in the same situations, but the MDIP contains only LifeCycleState header in the service responses, whereas in ALAP the complete set of headers is provided.
![image](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/57349523/806efe71-16cd-44ec-825d-4fcb428b9897)

**Comment by openBackhaul** [comment]
No parameters from out-of-MW-SDN-domain applications is correct.  
Only life-cycle-state header in response to out-of-MW-SDN-domain application is correct.  
Complete sets of parameters and headers from and to applications of the MW SDN domain applications are also correct.  
=> MDIP is fine.
