### ISSUE TITLE
Operation "bequeath-your-data-and-die" - backwardCompatibleUpdateOfOperation

### ISSUE THREAD

**Issue by pBittenbringMentopolis** [openBackhaul/MultiDomainInventoryProxy#8]
Callback: PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation
For this callback there is not much information available how it is to be implemented.
 
https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TinyApplicationController/RelayOperationUpdate.md
https://github.com/openBackhaul/MultiDomainInventoryProxy/blob/develop/spec/diagrams/09x_BequeathYourDataAndDie.png
 
As far as it is understood, this will broadcast info about new operations which will replace old operations. But for which operations of the MDIP this must be implemented? The "bequeath"-endpoint does receive info about name, release and address of newRelease, but is missing information about operations to be updated from oldRelease to newRelease. What is the source of information for this mapping when handling bequeath in oldRelease?

**Comment by openBackhaul** [comment]
PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation cannot be implemented in the initial version of an application.  
Some future version (Prompting**NewRelease**...) might need to ask the RegistryOffice to send a broadcast information about one of its new services is replacing an existing service in a backward compatible way, as soon as it got triggered by receiving a broadcast information about its own server is now replacing another existing server.
